### 1.0.0 成功案例
GET http://localhost:8000/api/resource-name?param1=value1&param2=123
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        client.assert(
            response.contentType.mimeType === "application/json",
            "Expected 'application/json' but received '" + response.contentType.mimeType + "'");
    });

    client.test("Response body is correct", function () {
        const body = JSON.stringify(response.body);
        const expect = JSON.stringify({
            "key": "value"
        });
        client.assert(
            body === expect,
            "received wrong body'" + body + "'"
        );
    });
%}

### 1.0.0 失敗案例
GET http://localhost:8000/api/resource-name?param1=value1
Accept: application/json

> {%
    client.test("Request failed as expected", function () {
        client.assert(response.status === 422, "Response status is not 422");
    });

    client.test("Response content-type is json", function () {
        client.assert(
            response.contentType.mimeType === "application/json",
            "Expected 'application/json' but received '" + response.contentType.mimeType + "'");
    });

    client.test("Response body is correct", function () {
        const body = JSON.stringify(response.body);
        const expect = JSON.stringify({
            "error": "錯誤訊息說明。"
        });
        client.assert(
            body === expect,
            "received wrong body'" + body + "'"
        );
    });
%}
